# Generated by Django 3.1.4 on 2021-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('word', models.CharField(max_length=30)),
                ('freq', models.IntegerField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
