# Generated by Django 3.1.4 on 2021-11-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Nouns',
        ),
    ]
