# Generated by Django 3.1.4 on 2021-11-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211116_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nouns',
            new_name='Noun',
        ),
    ]
